#include<SFML/Graphics.hpp>   //Graphics-Library

class CDrawableObject
{
public:
  CDrawableObject(std::string textureFile, float x, float y, float width, float height, float rotation);   //Constructor
  void render();   // rendering funktion
  sf::Sprite m_sprite;   // sprite generated by the texture
  sf::Texture m_texture;   // objects texture
  float m_height;   // object width
  float m_width;   // object height
  float m_x;   // x-Coords
  float m_y;   // y-Coords
  float m_rotation;   // The objects rotation
  char id;   // id for tracking purpose
};
